name: Update Data

on:
  push:
    paths:
      - 'data/**'
  schedule:
    - cron: '0 */6 * * *'  # 每6小时更新一次

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm install
        
      - name: Validate data
        run: node scripts/validate.js
        
      - name: Update timestamp
        run: node scripts/update-timestamp.js
        
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/
          git commit -m "Auto update data" || echo "No changes to commit"
          git push
